# This is a basic workflow to help you get started with Actions

name: M3U generator

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install requests yt-dlp

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
